/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtDragVerify: typeof import('./../components/core/ArtDragVerify.vue')['default']
    ArtFormDialog: typeof import('./../components/core/ArtFormDialog.vue')['default']
    ArtLogo: typeof import('./../components/core/ArtLogo.vue')['default']
    ArtSvgIcon: typeof import('./../components/ArtSvgIcon.vue')['default']
    ArtTable: typeof import('./../components/core/ArtTable.vue')['default']
    BasicSettings: typeof import('./../components/SettingsPanel/widgets/BasicSettings.vue')['default']
    BoxStyleSettings: typeof import('./../components/SettingsPanel/widgets/BoxStyleSettings.vue')['default']
    ColorSettings: typeof import('./../components/SettingsPanel/widgets/ColorSettings.vue')['default']
    ContainerSettings: typeof import('./../components/SettingsPanel/widgets/ContainerSettings.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./../components/SettingsPanel/widgets/SectionTitle.vue')['default']
    SettingActions: typeof import('./../components/SettingsPanel/widgets/SettingActions.vue')['default']
    SettingDrawer: typeof import('./../components/SettingsPanel/widgets/SettingDrawer.vue')['default']
    SettingHeader: typeof import('./../components/SettingsPanel/widgets/SettingHeader.vue')['default']
    SettingItem: typeof import('./../components/SettingsPanel/widgets/SettingItem.vue')['default']
    SettingsPanel: typeof import('./../components/SettingsPanel.vue')['default']
    ThemeSettings: typeof import('./../components/SettingsPanel/widgets/ThemeSettings.vue')['default']
    ThemeSvg: typeof import('./../components/core/ThemeSvg.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
